config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/science', to: 'pages#science', as: :science
  get '/fun', to: 'pages#fun', as: :fun
  get '/art', to: 'pages#art', as: :art
  get '/porn', to: 'pages#porn', as: :porn
  get '/spirituality', to: 'pages#spirituality', as: :spirituality
  get '/wtf', to: 'pages#wtf', as: :wtf
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/content.rb
class Content < ApplicationRecord
  has_many :comments
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  after_create :add_token

  private

  def add_token
    self.token = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    add_token if current_user
  end

  #use up token and redirect to chosen content
  def science
    deduct_token("science")
    if current_user.category == "science" && current_user.ticket.today?
      set_content("science")
      set_comments(@content.id)
    else
      denied
    end
  end

  def fun
    deduct_token("fun")
    if current_user.category == "fun" && current_user.ticket.today?
      set_content("fun")
      set_comments(@content.id)
    else
      denied
    end
  end

  def art
    deduct_token("art")
    if current_user.category == "art" && current_user.ticket.today?
      set_content("art")
      set_comments(@content.id)
    else
      denied
    end
  end

  def porn
    deduct_token("porn")
    if current_user.category == "porn" && current_user.ticket.today?
      set_content("porn")
      set_comments(@content.id)
    else
      denied
    end
  end

  def spirit
    deduct_token("spirit")
    if current_user.category == "spirit" && current_user.ticket.today?
      set_content("spirit")
      set_comments(@content.id)
    else
      denied
    end
  end

  def wtf
    deduct_token("wtf")
    if current_user.category == "wtf" && current_user.ticket.today?
      set_content("wtf")
      set_comments(@content.id)
    else
      denied
    end
  end

  private
  
  #if ticket is 1 day or more ago, add token and reset category
  def add_token
    if (Time.now.to_date - current_user.ticket).to_i > 0
      current_user.token = true
      current_user.category = nil
      current_user.save
    end
  end

  #if user has a token, remove it and add a ticket for today's category
  def deduct_token(page)
    if current_user.token
      current_user.token = false
      current_user.ticket = Time.now.to_date
      current_user.category = page
      current_user.save
    end
  end
  #if user has no token, redirect to home and display notice
  def denied
    if current_user.category == nil
      redirect_to root_path, notice: "Make your choice"
    elsif current_user.category && !current_user.ticket.today?
      redirect_to root_path, notice: "Make your choice"
    else
      redirect_to root_path, notice: "You chose #{current_user.choice} today. One a day you greedy cunt. "
    end
  end

  def set_content(category)
    #do the following only once a day
    #select the content container of that category
    category_content = Content.where(category: category)
    #returns hash/array? of Content instances
    #remove content the user has already seen from the array
    category_content.each do |content|
      content.user_id 

reject(:user_id == current_user.id)
    seen.each do |id|
      category_content = category_content.reject!(|content| content.id == id)
    end
    #select a new random content from the container
    @content = seen.sample
    #add user id to content
  end

  def set_comments(id)
    @comments = Comment.where(content_id: id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handpickd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-header">
      <h1><a href="/">handpick'd</a></h1>
      <p>one handpicked piece of entertainment once a day. pick your poison:</p>
    </div>
    <br>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/art.html.erb
<h1>art</h1>

app/views/pages/fun.html.erb
<h1>fun</h1>

<%= image_tag @content, id: "content" %>
<div class="comments">
  <%= form_for @comments %>
    <%= f.input :name %>
    <%= f.input :comment, as: :text %>
    <%= f.submit %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="containe">
  <div class="options-container">
    <div class="row">
      <div class="option option-link col-10 col-lg-3">
        <%= link_to "", science_path %>
        <div class="option-description">
          <h4>Fernando, what does the future hold?</h4>
        </div>
        <div class="option-header" id="science">
          <h2>science</h2>
        </div>
      </div>
      <div class="option option-link col-10 col-lg-3" id="fun">
        <%= link_to "", fun_path %>
        <div class="option-description">
          <h4>Make me chuckle</h4>
        </div>
        <div class="option-header">
          <h2>fun</h2>
        </div>
      </div>
      <div class="option option-link col-10 col-lg-3" id="wtf">
        <%= link_to "", wtf_path %>
        <div class="option-description">
          <h4>Baffle me</h4>
        </div>
        <div class="option-header">
          <h2>wtf</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="option option-link col-10 col-lg-3" id="art">
        <%= link_to "", art_path %>
        <div class="option-description">
          <h4>Show me something beautiful</h4>
        </div>
        <div class="option-header">
          <h2>art</h2>
        </div>
      </div>
      <div class="option option-link col-10 col-lg-3" id="porn">
        <%= link_to "", porn_path %>
        <div class="option-description">
          <h4>Penises, skin and fluids</h4>
        </div>
        <div class="option-header">
          <h2>porn</h2>
        </div>
      </div>
      <div class="option option-link col-10 col-lg-3" id="spirituality">
        <%= link_to "", spirituality_path %>
        <div class="option-description">
          <h4>Enlighten me</h4>
        </div>
        <div class="option-header">
          <h2>spirituality</h2>
        </div>
      </div>
    </div>
  </div>
    <div class="content">
    <% if current_user && current_user.ticket.today? %>
      <%#= render 'content', object: @content %>
    <% end %>
    </div>
</div>

app/views/pages/porn.html.erb
<h1>porn</h1>

app/views/pages/science.html.erb
<h1>science</h1>

app/views/pages/spirit.html.erb
<!--<iframe width="800" height="600" src="http://www.youtube.com/embed/<% @spirituality %>" frameborder="0"></iframe>-->
<div class="content">
  <p>You don't need coffee; you need sleep.</p>
  <p>You don't need nicotine; you need to walk.</p>
  <p>You don't need booze; you need to laugh hard.</p>
  <p>You don't need sex; you need connection.</p>
  <p>You don't need to scream; you need to express yourself.</p>
  <p>You don't need to tragic; you need to listen.</p>
  <p>You don't need synthetic drugs; you need art.</p>
  <p>You don't need inspiring; you need to be hugged.</p>
  <p>You don't need TV; you need poetry.</p>
  <p>You don't need to buy; you need Nature.</p>
  <p>You don't need to judge, you need empathy.</p>
  <p>You don't need religions; you need questions.</p>
  <p>You don't need love relationships; you need self love.</p>
  <p>You need your self.</p>
  <p>I need me.</p>
  <p>Above everything you need inner peace, which requires harmony between the inside and the outside.</p>
  <p>Do what you believe and believe in what you do.</p>
</div>

app/views/pages/spirituality.html.erb
<!--<iframe width="800" height="600" src="http://www.youtube.com/embed/<% @spirituality %>" frameborder="0"></iframe>-->
<div class="content">
  <p>You don't need coffee; you need sleep.</p>
  <p>You don't need nicotine; you need to walk.</p>
  <p>You don't need booze; you need to laugh hard.</p>
  <p>You don't need sex; you need connection.</p>
  <p>You don't need to scream; you need to express yourself.</p>
  <p>You don't need to tragic; you need to listen.</p>
  <p>You don't need synthetic drugs; you need art.</p>
  <p>You don't need inspiring; you need to be hugged.</p>
  <p>You don't need TV; you need poetry.</p>
  <p>You don't need to buy; you need Nature.</p>
  <p>You don't need to judge, you need empathy.</p>
  <p>You don't need religions; you need questions.</p>
  <p>You don't need love relationships; you need self love.</p>
  <p>You need your self.</p>
  <p>I need me.</p>
  <p>Above everything you need inner peace, which requires harmony between the inside and the outside.</p>
  <p>Do what you believe and believe in what you do.</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="text-center">
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-hp">
    <% if current_user %>
    <ul id="logout">
        <li>L</li>
        <li>O</li>
        <li>G</li>
        <li> </li>
        <li>O</li>
        <li>U</li>
        <li>T</li>
    </ul>
    <%#= link_to "", user_profile_path, class: "user-btn" %>
        <%= link_to "", destroy_user_session_path, method: :delete, class: "logout-btn" %>
    <% else %>
        <%= link_to "", new_user_session_path, class: "login-btn" %> 
        <ul id="login">
            <li>L</li>
            <li>O</li>
            <li>G</li>
            <li> </li>
            <li>I</li>
            <li>N</li>
        </ul>
    <% end %>
</div>